-- ============================================
-- PWJ Tracker - Seed Data (H2 Compatible)
-- ============================================

INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-19 18:38:00','Sakthiganesh','Niwin','001','Granite','Lakshmi red Natural','Shri kota stones','Nos',5,'2026-01-23','PROCEED','Shri kota stones',true,'CLOSED','2026-01-23','Material delivered at site',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-19 18:42:00','Sakthi ganesh','Niwin','002','Tile','300mm x 300mm','Rak/Kajaria','Nos',300,'2026-01-24','HOLD','-',false,'OPEN',null,'Need Bharath sir approval to proceed',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-19 18:51:00','Sakthiganesh','Niwin','003','Cement OPC','OPC','Chettinadu/Ramco','Nos',20,'2026-01-23','PROCEED','Ramesh',true,'CLOSED',null,'PO released; site team told hold delivery',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-19 19:01:00','Sakthiganesh','Niwin','004','P Sand','-','-','Unit',1,'2026-01-25','PROCEED','-',false,'OPEN',null,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-21 15:22:00','Sakthiganesh','Niwin','005','Tile Adhesive','-','Somany/Myk','Nos',20,'2026-01-24','PROCEED','-',true,'CLOSED','2026-01-24','',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-21 19:38:00','Sakthiganesh','Niwin','006','Cat 6 Cable','4 pair/gray colour','D-link','Meter',200,'2026-01-23','HOLD','-',true,'CLOSED','2026-01-24','Material delivered at site',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-24 17:12:00','P.Yogesh','Spectra PV Mahalingapuram','18','Electrical Material','2.5sqmm+1.5sqmm wire+accessories','Orbit','Lot',1,'2026-01-27','PROCEED','Oshwal Traders',true,'CLOSED','2026-01-28','Material delivered at site',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-25 10:29:00','P.Yogesh','Spectra Mahalingapuram','2','Teak Wooden Beading','19mmx9mm cove beading','Local','Rft',300,'2026-01-28','NOT_APPROVED','-',false,'OPEN',null,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-25 10:33:00','P.Yogesh','Spectra Mahalingapuram','NT','Door Frame','3.5x2 inches 7ft height','Factory','Nos',1,'2026-01-27','PROCEED','KPS Traders',true,'CLOSED',null,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-27 17:52:00','P.Yogesh','Spectra Mahalingapuram','11,12','Grid Ceiling Material','Main Tee, 2ft channel, Wall angle, Grid tile, J hook','PVC','Nos',1,'2026-01-29','PROCEED','Sam Ceiling',true,'CLOSED','2026-02-03','PO issued; material delivered',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-27 17:58:00','P.Yogesh','Spectra Mahalingapuram','-','GI Full Height Gypsum Partition','75mm with glass','Xpert','Sqft',145,'2026-01-29','PROCEED','G.Saravanan',true,'CLOSED',null,'WO issued; work ongoing at site',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-27 18:00:00','P.Yogesh','Spectra Mahalingapuram','13','100mm Aluminium Partition','Double skin board','USG Knaug','Sqft',140,'2026-01-30','PROCEED','G.Saravanan',true,'CLOSED',null,'WO issued; work ongoing at site',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-27 18:05:00','P.Yogesh','Spectra Mahalingapuram','2','Premium Emulsion Painting','Putty+primer+2 coats','Asian/Nippon','Sqft',7300,'2026-01-29','PROCEED','G.Saravanan',true,'CLOSED',null,'WO issued; work ongoing at site',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-27 18:07:00','P.Yogesh','Spectra Mahalingapuram','31,30','Enamel Painting','Primer+Enamel 2 coat','Asian','Sqft',270,'2026-01-29','PROCEED','G.Saravanan',true,'CLOSED',null,'WO issued; work ongoing at site',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-27 18:09:00','P.Yogesh','Spectra Mahalingapuram','13','Premium Emulsion Painting 2nd Area','2 coat putty+primer+2 coats','Asian','Sqft',700,'2026-01-30','PROCEED','G.Saravanan',true,'CLOSED',null,'WO issued; work ongoing at site',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-27 18:14:00','P.Yogesh','Spectra Mahalingapuram','35,36','Plumbing Fixtures','EWC 2nos, Washbasin, Health faucet, Taps','Parryware','Set',1,'2026-01-31','HOLD','Oswal Ceramic',true,'CLOSED',null,'PO issued; delivery by 02.02.2026',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-27 18:39:00','P.Yogesh','Spectra Mahalingapuram','15','MD Table with Pedestal','1200mmx900mm factory finish','Factory','Nos',1,'2026-02-02','HOLD','-',false,'OPEN',null,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-27 18:59:00','P.Yogesh','Spectra Mahalingapuram','17&25','Workstation Table','Back-to-back 30nos + linear 10nos','Factory','Nos',40,'2026-02-05','PROCEED','Green Design',true,'CLOSED','2026-02-16','PO issued; delivery by 16.02.2026',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-27 19:00:00','P.Yogesh','Spectra Mahalingapuram','22','File Storage','Pre lam board','Factory','Sqft',52,'2026-02-05','HOLD','-',false,'CLOSED',null,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-28 18:49:00','P.Yogesh','Spectra Mahalingapuram','9&5','Laminate','Reception wall 683Got/263MOK','Delta','Nos',4,'2026-01-30','PROCEED','KPS Traders',true,'CLOSED','2026-01-31','',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-28 19:04:00','P.Yogesh','Spectra Mahalingapuram','3&29','Square Concealed Light 12W','9x9 cool white','Katlux','Nos',48,'2026-02-02','PROCEED','Spark Electricals',true,'CLOSED','2026-01-29','PO issued; delivery by 30.01.2026',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-28 19:06:00','P.Yogesh','Spectra Mahalingapuram','11','Grid Tile Light 2x2ft','2ft x 2ft square cool white','Phillips','Nos',25,'2026-02-02','PROCEED','Patel Electricals',true,'CLOSED','2026-01-30','PO issued; delivery by 30.01.2026',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-30 11:46:00','P.Yogesh','Spectra Mahalingapuram','11 add','Grid Ceiling Additional Qty','Main tee 5, 2ft channel 15, wall angle 10','Sam Ceiling','Nos',1,'2026-02-02','PROCEED','Sam Ceiling',true,'CLOSED','2026-02-02','PO issued',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-01-31 17:05:00','P.Yogesh','Spectra Mahalingapuram','10','Mirror','6mm 36.5W x 93.75H inches','Factory','Nos',1,'2026-02-03','PROCEED','-',false,'OPEN',null,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-02 18:58:00','Sakthi ganesh','Niwin','011','Wooden Props','Natural wood','-','Nos',30,'2026-02-04','PROCEED','-',false,'OPEN',null,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-02 19:22:00','Sakthiganesh','Niwin','012','Wire 1.5sqmm','Red-2, Yellow-1, Blue-1','Orbit','Coil',4,'2026-02-05','PROCEED','Oshwal Traders',true,'CLOSED','2026-02-06','PO issued',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-03 11:43:00','Sakthiganesh','Niwin - Saravanan','-','Cat6 Cable Laying','NA','-','Meter',200,'2026-02-04','PROCEED','G.Saravanan',true,'CLOSED','2026-02-04','WO issued to vendor 04.02.2026',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-03 12:29:00','Sakthiganesh','Niwin - Vivek','-','Supply and Fixing Unjal Hook','-','-','Set',2,'2026-02-04','PROCEED','Vivek',true,'CLOSED','2026-02-04','WO issued',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-04 10:10:00','Sakthiganesh','Niwin - Feruddtin','-','Granite Skirting Laying','-','-','Rft',500,'2026-02-04','PROCEED','Feruddtin',true,'CLOSED','2026-02-04','WO issued',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-04 11:40:00','P.Yogesh','Spectra Mahalingapuram','18,27','Electrical Wire Additional','4sqmm+2.5sqmm+1.5sqmm','Orbit','Coil',1,'2026-02-05','PROCEED','Oshwal Traders',true,'CLOSED','2026-02-06','',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-04 17:04:00','Jagan K','MG Select Nandhanam','NT','Aluminium Skirting Installation','NA','NA','Rft',450,'2026-02-04','PROCEED','Saravanan',true,'CLOSED',null,'Work completed at site',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-06 10:38:00','P.Yogesh','Spectra Mahalingapuram','NT Revised','Plywood and Hardware Revised','16mm ply 2nos, 12mm ply 7nos, laminates','Mr Commercial/Delta','Nos',1,'2026-02-07','PROCEED','KPS Traders',true,'CLOSED','2026-02-06','Bharat sir approved orally',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-06 16:00:00','P.Yogesh','Spectra Mahalingapuram','-','Grid Ceiling Channel Additional','2ft ch 120, 4ft ch 60, Main tee 18, Wall angle 10','Sam Ceiling','Nos',1,'2026-02-07','PROCEED','Shoya Ceiling',true,'CLOSED','2026-02-09','',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-06 17:27:00','P.Yogesh','Spectra Mahalingapuram','3&29 add','Concealed LED Light 12W','9x9 12watts','Kaltex','Nos',12,'2026-02-09','PROCEED','Spark Electrical',true,'CLOSED','2026-02-09','',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-06 17:44:00','Vidhya','Admin Office','-','RO Water Purifier','RO+UV+UF, 10-15 LPH','Any good quality','Nos',1,'2026-02-15','PROCEED','-',false,'OPEN',null,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-07 14:09:00','Sakthiganesh','Niwin','012','Steel 12mm Rod','Fe-550 GBR','-','Nos',12,'2026-02-10','PROCEED','Om Sherma',true,'CLOSED','2026-02-10','PO issued',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-07 14:22:00','Sakthiganesh','Niwin','012','Steel 10mm Rod','GBR','-','Nos',4,'2026-02-10','PROCEED','Om Sherma',true,'CLOSED','2026-02-10','PO issued',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-09 09:04:00','P.Yogesh','Spectra Mahalingapuram','18,27','Electrical Switches and Plates','Anchor Roma 6M plates 55nos, switches, sockets','Anchor Roma','Nos',1,'2026-02-10','PROCEED','Oswal Traders',true,'CLOSED','2026-02-10','PO issued',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-09 10:27:00','Sakthiganesh','Niwin','005','Cement PPC','-','Ramco/Chettinadu','Bags',20,'2026-02-12','PROCEED','Krishna Traders',true,'CLOSED','2026-02-14','PO issued',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-09 14:46:00','Santhosh Kumar','Spectra Mahalingapuram','NT','Laminate 683Got','Delta','Delta','No',7,'2026-02-10','HOLD','-',false,'CLOSED',null,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-09 15:46:00','Santhosh Kumar','Spectra','4','Wallpaper 7519-05','Eco-project vol.X','-','Sqft',100,'2026-02-12','PROCEED','Wall Jewel Line',true,'CLOSED','2026-02-16','PO issued',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-09 17:48:00','Sakthiganesh','Naresh','001','Bore Well','NA','-','Feet',45,'2026-02-12','PROCEED','Sekar Bore Well',true,'CLOSED',null,'WO issued; complete by 14.02.2026',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-09 17:53:00','Sakthiganesh','Niwin','015','Waterproofing','NA','-','Sqft',487,'2026-02-11','NOT_APPROVED','Dharasitha Water Proofing',true,'CLOSED',null,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-10 10:54:00','Santhosh Kumar','Spectra PV Mahalingapuram','NT','Carpenter Works GF Panelling','-','G.Saravanan','Sqft',259,'2026-02-10','PROCEED','G.Saravanan',true,'CLOSED','2026-02-10','WO issued',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-10 17:43:00','Santhosh Kumar','Spectra','11','Grid Ceiling 4ft Channel','1200mm channel','Sam Ceiling','Nos',95,'2026-02-11','PROCEED','Shoya Ceilings',true,'CLOSED','2026-02-12','PO issued',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-11 11:13:00','Jagan K','Sai Retro','-','Solid Blocks 6x8x16 inch','NA','-','Nos',500,'2026-02-13','PROCEED','Jeyam Bricks',true,'CLOSED','2026-02-13','',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-11 11:30:00','Sakthiganesh','Niwin','001','M Sand','NA','-','Units',1.5,'2026-02-13','PROCEED','Jeyam Bricks',true,'CLOSED',null,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-16 12:09:00','Bhaskaran A','Century Plyboards','NT-63','Vacuum Puller Single Cup','-','Multi Tech Industries','Nos',10,'2026-02-18','PROCEED','Multi Tech Industry',true,'CLOSED','2026-02-21','PO issued',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-16 16:49:00','Bhaskaran A','Official','-','Laser Measuring Device GLM-40','-','Bosch','Nos',1,'2026-02-19','HOLD','-',false,'CLOSED',null,'No approval',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-17 10:10:00','Sakthiganesh','Naresh','005','Steel Rods Various','16mm-45, 12mm-115, 10mm-21, 8mm-80, binding wire 25kg','GBR','Nos',1,'2026-02-20','PROCEED','RLP and Co',true,'CLOSED','2026-02-23','PO issued',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-20 14:30:00','Bhaskaran A','Official','-','Laser Measuring Instrument GLM-50','-','Bosch','Numbers',1,'2026-02-27','NOT_APPROVED','Amazon',false,'OPEN',null,'Need to place order',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-20 14:51:00','Sakthiganesh','Niwin','001','Door Frame','5x3 inch natural wood','Natural Wood','Nos',13,'2026-02-21','PROCEED','-',false,'CLOSED',null,'Waiting for Bharath sir approval',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-20 17:05:00','Santhosh Kumar','Spectra','NT','Wallpaper 7519-05 additional','Eco-project vol.X','-','Sqft',100,'2026-02-23','PROCEED','Wall Jewel Line',true,'CLOSED','2026-02-25','WO issued; complete by 25.02.2026',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-23 10:31:00','Sakthi Ganesh','Niwin Residence Neelankarai','001','Filling Soil','Natural sand','-','Units',2.5,'2026-02-24','PROCEED','Priya Traders',true,'CLOSED','2026-02-25','PO issued',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-23 11:03:00','Jagan','Sai Retro Mountroad','-','M Sand Rough','For block work','NA','Cft',100,'2026-02-24','PROCEED','R.Ramesh',true,'CLOSED','2026-02-26','PO issued',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-23 12:35:00','Jagan','Sai Retro Mountroad','-','RMC M20','NA','NA','Cubic Meter',15,'2026-03-02','PROCEED','-',false,'CLOSED',null,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-23 13:02:00','Jagan','Sai Retro Mountroad','-','MS Rod Various','8mm-55, 10mm-160, 12mm-20, 16mm-2, binding wire 30kg','NA','Kg',1,'2026-02-27','NOT_APPROVED','-',false,'CLOSED',null,'Not approved - wrong qty',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-25 08:07:00','Sakthi Ganesh','Niwin Residence Neelankarai','005','Closet White','Kohler Patio wall mount','Kohler','Nos',1,'2026-02-27','PROCEED','Abhivarivan',true,'OPEN',null,'PO released; delivery by 04.03.2026',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-25 13:03:00','Jagan','Sai Retro Mountroad','-','Mild Steel','8mm-40, 10mm-80, 12mm-32, 16mm-3, binding wire 10kg','JSW','Kg',1,'2026-02-27','PROCEED','Annai Auxilium',true,'CLOSED','2026-02-26','Material delivered at site',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-25 15:09:00','Sakthi Ganesh','Niwin Residence Neelankarai','005','Wooden Props 20ft','Natural wood','-','Nos',15,'2026-02-27','PROCEED','Madha',true,'CLOSED','2026-02-27','Material delivered at site',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-25 15:14:00','Sakthi Ganesh','Niwin Residence Neelankarai','001','Electrical Wire','1.5sqmm, 2.5sqmm, 6sqmm','Orbit','Coil',1,'2026-02-27','PROCEED','Oswal Traders',true,'CLOSED','2026-03-02','PO issued',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-25 15:16:00','Sakthi Ganesh','Niwin Residence Neelankarai','012','Bricks 9x3x4 inch','Wirecut/chamber','-','Nos',1000,'2026-02-27','PROCEED','Kumar Traders',true,'CLOSED','2026-02-28','PO issued',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-26 12:52:00','Sakthi Ganesh','Niwin Residence Neelankarai','001','3/4 Aggregate','Stone crushed','-','Unit',1,'2026-02-28','PROCEED','Kumar Traders',true,'CLOSED',null,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-26 12:54:00','Sakthi Ganesh','Niwin Residence Neelankarai','010','Cement PPC','-','Ramco','Bags',20,'2026-02-28','PROCEED','Kumar Traders',true,'CLOSED',null,'',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-26 13:43:00','Sakthi Ganesh','Niwin Residence Neelankarai','020','Rainwater Harvesting Pile','Pile work 10ft','-','Nos',2,'2026-03-02','PROCEED','Dhana Sekar',true,'CLOSED',null,'WO issued; start by 03.03.2026',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO pwj_entry (timestamp, raised_by, project_name, boq_no, material_required, specification, brand, unit, quantity, date_of_requirement, approval_status, vendor, pwj_issued, status, delivered_date, remarks, created_at, updated_at) VALUES ('2026-02-27 14:01:00','Jagan','Sai Retro Mountroad','-','Louvers/Smoke Window','450mmx450mm aluminium/UPVC','-','Nos',1,'2026-03-06','PROCEED','Urban Window',true,'OPEN',null,'PO released; delivery by 04.03.2026',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);

-- ============================================
-- USERS (admin / engineers / procurement)
-- ============================================
INSERT INTO app_user (username, password, full_name, email, role, active, created_at, updated_at) VALUES ('admin', 'admin123', 'Administrator', 'admin@pwj.com', 'ADMIN', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO app_user (username, password, full_name, email, role, active, created_at, updated_at) VALUES ('procurement', 'proc123', 'Procurement Team', 'procurement@pwj.com', 'PROCUREMENT', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO app_user (username, password, full_name, email, role, active, created_at, updated_at) VALUES ('sakthiganesh', 'eng123', 'Sakthiganesh', 'sakthi@pwj.com', 'ENGINEER', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO app_user (username, password, full_name, email, role, active, created_at, updated_at) VALUES ('yogesh', 'eng123', 'P. Yogesh', 'yogesh@pwj.com', 'ENGINEER', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO app_user (username, password, full_name, email, role, active, created_at, updated_at) VALUES ('jagan', 'eng123', 'Jagan K', 'jagan@pwj.com', 'ENGINEER', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO app_user (username, password, full_name, email, role, active, created_at, updated_at) VALUES ('santhosh', 'eng123', 'Santhosh Kumar', 'santhosh@pwj.com', 'ENGINEER', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO app_user (username, password, full_name, email, role, active, created_at, updated_at) VALUES ('bhaskaran', 'eng123', 'Bhaskaran A', 'bhaskaran@pwj.com', 'ENGINEER', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO app_user (username, password, full_name, email, role, active, created_at, updated_at) VALUES ('anusha', 'anu', 'Anusha', 'anusha@happizo.com', 'ENGINEER', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ============================================
-- VENDORS
-- ============================================
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Shri Kota Stones', 'Stone & Granite', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Oshwal Traders', 'Electrical', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('KPS Traders', 'Hardware & Carpentry', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Sam Ceiling', 'Ceiling Works', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Shoya Ceilings', 'Ceiling Works', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('G.Saravanan', 'Civil Works', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Green Design', 'Furniture', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Spark Electricals', 'Electrical', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Patel Electricals', 'Electrical', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Oswal Ceramic', 'Sanitary & Tiles', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Wall Jewel Line', 'Wallpaper', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Sekar Bore Well', 'Civil Works', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Krishna Traders', 'Building Materials', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Jeyam Bricks', 'Building Materials', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Om Sherma', 'Steel & Iron', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('RLP & Co', 'Steel & Iron', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Annai Auxilium', 'Steel & Iron', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Guna Sekar', 'Civil Works', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Multi Tech Industry', 'Tools & Equipment', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Kumar Traders', 'Building Materials', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Priya Traders', 'Building Materials', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('R.Ramesh', 'Sand & Aggregate', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Abhivarivan', 'Sanitary & Plumbing', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Madha', 'Civil Works', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Urban Window', 'Windows & Glass', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Dhana Sekar', 'Civil Works', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Amazon', 'Online Purchase', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Ramesh', 'Building Materials', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Saravanan', 'Civil Works', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Vivek', 'Civil Works', true, CURRENT_TIMESTAMP, 'APPROVED');
INSERT INTO vendor (name, category, active, created_at, status) VALUES ('Feruddtin', 'Civil Works', true, CURRENT_TIMESTAMP, 'APPROVED');
